# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.AuthGroup')),
            ],
            options={
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.AuthGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.AuthUser')),
            ],
            options={
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.AuthPermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.AuthUser')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='CoilDetails',
            fields=[
                ('coil_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coil_name', models.CharField(max_length=100)),
                ('coil_notes', models.CharField(max_length=8000)),
            ],
            options={
                'db_table': 'coil_details',
            },
        ),
        migrations.CreateModel(
            name='DateDetails',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_date', models.DateField()),
                ('coil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.CoilDetails')),
            ],
            options={
                'db_table': 'date_details',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='GradsysDetails',
            fields=[
                ('gradsys_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gradsys_name', models.CharField(max_length=100)),
                ('gradsys_notes', models.CharField(max_length=8000)),
            ],
            options={
                'db_table': 'gradsys_details',
            },
        ),
        migrations.CreateModel(
            name='PhantomDetails',
            fields=[
                ('phantom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phantom_name', models.CharField(max_length=100)),
                ('phantom_notes', models.CharField(max_length=8000)),
            ],
            options={
                'db_table': 'phantom_details',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=100)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.DateDetails')),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='ScannerDetails',
            fields=[
                ('scanner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scanner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('scanner_notes', models.CharField(blank=True, max_length=8000, null=True)),
            ],
            options={
                'db_table': 'scanner_details',
            },
        ),
        migrations.CreateModel(
            name='SeriesDetails',
            fields=[
                ('series_id', models.IntegerField(primary_key=True, serialize=False)),
                ('series', models.CharField(max_length=100)),
                ('series_notes', models.CharField(max_length=8000)),
            ],
            options={
                'db_table': 'series_details',
            },
        ),
        migrations.CreateModel(
            name='VersionDetails',
            fields=[
                ('version_id', models.IntegerField(primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=100)),
                ('version_notes', models.CharField(max_length=8000)),
            ],
            options={
                'db_table': 'version_details',
            },
        ),
        migrations.AddField(
            model_name='results',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.SeriesDetails'),
        ),
        migrations.AlterUniqueTogether(
            name='djangocontenttype',
            unique_together=set([('app_label', 'model')]),
        ),
        migrations.AddField(
            model_name='djangoadminlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.DjangoContentType'),
        ),
        migrations.AddField(
            model_name='djangoadminlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.AuthUser'),
        ),
        migrations.AddField(
            model_name='datedetails',
            name='gradsys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.GradsysDetails'),
        ),
        migrations.AddField(
            model_name='datedetails',
            name='phantom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.PhantomDetails'),
        ),
        migrations.AddField(
            model_name='datedetails',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ScannerDetails'),
        ),
        migrations.AddField(
            model_name='datedetails',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.VersionDetails'),
        ),
        migrations.AddField(
            model_name='authpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.DjangoContentType'),
        ),
        migrations.AddField(
            model_name='authgrouppermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.AuthPermission'),
        ),
        migrations.AlterUniqueTogether(
            name='authuseruserpermissions',
            unique_together=set([('user', 'permission')]),
        ),
        migrations.AlterUniqueTogether(
            name='authusergroups',
            unique_together=set([('user', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='authpermission',
            unique_together=set([('content_type', 'codename')]),
        ),
        migrations.AlterUniqueTogether(
            name='authgrouppermissions',
            unique_together=set([('group', 'permission')]),
        ),
    ]
